# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11gF5ljinP5VroF96a99XzAWs_GJ3RGGo
"""

#Bir liste belirleyip bu listedeki elemanları tersine çevireceğiz
def ters(liste):
  new_list = liste[::-1]
  return new_list

liste=["Bilge","Can","Rodi",9,24,1,2]
print(ters(liste))



#eğer liste içinde listeleri ters çevirmek istersek bu yöntemi kullanabiliriz
b=[[16,8],[9,24],[2,5]]
def new_list(b):
  for i in b:
      i.reverse()
  b.reverse()
  return(b)

new_list(b)

